//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eportafolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public string linkedin { get; set; }
        public string website { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Skills { get; set; }
        public string Tools { get; set; }
    }
}
